### ISSUE TITLE
TestShell errors

### ISSUE THREAD

**Issue by b23prodtm** [b23prodtm/myphpcms#33]
```
Error: Database connection "Mysql" is missing, or could not be created.
#0 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Model/Datasource/DboSource.php(271): Mysql->connect()
#1 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/TestSuite/Fixture/CakeFixtureManager.php(92): ConnectionManager::getDataSource('test')
#3 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/TestSuite/Fixture/CakeFixtureManager.php(71): CakeFixtureManager->_initDb()
#4 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/TestSuite/CakeTestRunner.php(62): CakeFixtureManager->fixturize(Object(ShellTest))
#5 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/TestSuite/CakeTestSuiteCommand.php(98): CakeTestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#6 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/Command/TestShell.php(283): CakeTestSuiteCommand->run(Array)
#7 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/Command/TestShell.php(268): TestShell->_run(Array, Array)
#8 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/Shell.php(462): TestShell->main()
#9 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('core', Array)
#10 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /Users/travis/build/b23prodtm/myphpcms/lib/Cake/Console/cake.php(54): ShellDispatcher::run(Array)
#12 {main}
The command "if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then if [ '${PHPCS}' != '1' ]; then ./lib/Cake/Console/cake test core AllTests --stderr; else app/vendor/bin/phpcs -p --extensions=php --standard=CakePHP ./lib/Cake; fi; fi" exited with 244.
0.85s$ php app/vendor/bin/phpunit --coverage-php .travis/TravisCI-OSX-PHP/build/cov/coverage-${component_name}.cov . | grep error
Fatal error: require_once(): Failed opening required '/Users/travis/build/b23prodtm/myphpcms/Plugin/DebugKit/Test/CaseDSDebugkitGroupTestCase.php' (include_path='.:') in /Users/travis/build/b23prodtm/myphpcms/Plugin/DebugKit/Test/Case/AllDebugKitTest.php on line 19
````

**Comment by b23prodtm** [comment]
Upon composer update 
> Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^5.6 but your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for php-coveralls/php-coveralls ^2.1 -> satisfiable by php-coveralls/php-coveralls[v2.1.0].
    - php-coveralls/php-coveralls v2.1.0 requires php ^5.5 || ^7.0 -> your PHP version (5.4.45) does not satisfy that requirement.

```
$ curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6
```
